In [1]:
%matplotlib inline
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel("VIGNESH121.xlsx")
df.head()

                    names     alias unit   price    MTL_CODE
0            0-15 AMMETER   AMMETER   NO    1.81  9029262907
1          0-150A AMMETER   AMMETER   NO   55.03  4970090140
2      0-150-300A AMMETER   AMMETER   NO   99.58  9029108100
3         0-1000A AMMETER   AMMETER   NO  215.35  9099432089
4  0-150-600-1250 AMMETER   AMMETER   NO  740.95  9049251230

In [3]:
d={"NO":100,"MR":80,"KG":60,"ST":45,"LT":35,"SM":25,"LO":17,"MT":15,"RL":13,"QM":11,"SH":9,"PR":7,"PK":6,"PD":5,"CM":4,"KL":3,"HN":2,"RM":1,"LB":0.5,"GM":0.25}
df['unit']=df['unit'].map(d)
df.head()

                    names     alias   unit   price    MTL_CODE
0            0-15 AMMETER   AMMETER  100.0    1.81  9029262907
1          0-150A AMMETER   AMMETER  100.0   55.03  4970090140
2      0-150-300A AMMETER   AMMETER  100.0   99.58  9029108100
3         0-1000A AMMETER   AMMETER  100.0  215.35  9099432089
4  0-150-600-1250 AMMETER   AMMETER  100.0  740.95  9049251230

In [5]:
features=['unit','price']
df1=df[features]

In [6]:
df2=df[:1000]
df3=df1[:1000]

In [7]:
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(df3)

In [15]:
km=KMeans(n_clusters=400,init='k-means++',n_init=10,algorithm = 'auto',max_iter=400)
km.fit(X_scaled)
df2['cluster']=km.fit_predict(X_scaled)
df2[:20]

C:\Users\Acer\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,names,alias,unit,price,MTL_CODE,cluster
0,0-15 AMMETER,AMMETER,100.0,1.81,9029262907,390
1,0-150A AMMETER,AMMETER,100.0,55.03,4970090140,208
2,0-150-300A AMMETER,AMMETER,100.0,99.58,9029108100,280
3,0-1000A AMMETER,AMMETER,100.0,215.35,9099432089,285
4,0-150-600-1250 AMMETER,AMMETER,100.0,740.95,9049251230,259
5,"0.50X780XCOIL,CRNGO,SPEC-AA10916.",COIL,80.0,10.65,2851244930,339
6,"0.50X615MMXCOIL,CRNGO,SPEC-AA10915.",COIL,80.0,11.09,2851244922,339
7,"0.50X985XCOIL,CRNGO,SHT,SPEC-HG10062",COIL,80.0,11.80,2851244949,339
8,"0.50X785XCOIL,SPEC-AA10915.",COIL,80.0,12.98,2851244930,224
9,0.35 X 540 X COIL,COIL,80.0,22053.92,4670274090,21
10,0.50 X 892 X COIL,COIL,100.0,26.74,9099468784,398
11,0.50 X 892 X COIL,COIL,100.0,372.71,9069461102,303
12,0.50 X 892 X COIL,COIL,100.0,376.06,9069432803,303
13,0.35 X 780 X COIL,COIL,100.0,612.10,4323027923,352
14,0.50 X 495 MM X COILCRNGO (AA10901),COIL,100.0,3743.12,4981667030,22
15,0.4TKX50 COTTON TAPE,COTTON TAPE,60.0,116.00,2289026018,116
16,0.4TKX50 COTTON TAPE,COTTON TAPE,60.0,10356.78,7701505010,37
17,0.4X200 MM COPPER SHEET,COTTON TAPE,60.0,43050.00,1477806010,19
18,0.4TKX50 COTTON TAPE,COTTON TAPE,80.0,3.31,2851244850,145
19,0.4TKX50 COTTON TAPE,COTTON TAPE,80.0,5.43,2851244850,145

In [14]:
df2.sort_values(["alias","unit","price","MTL_CODE"])[:20]

,names,alias,unit,price,MTL_CODE,cluster
0,0-15 AMMETER,AMMETER,100.0,1.81,9029262907,383
1,0-150A AMMETER,AMMETER,100.0,55.03,4970090140,341
2,0-150-300A AMMETER,AMMETER,100.0,99.58,9029108100,216
3,0-1000A AMMETER,AMMETER,100.0,215.35,9099432089,303
4,0-150-600-1250 AMMETER,AMMETER,100.0,740.95,9049251230,252
5,"0.50X780XCOIL,CRNGO,SPEC-AA10916.",COIL,80.0,10.65,2851244930,251
6,"0.50X615MMXCOIL,CRNGO,SPEC-AA10915.",COIL,80.0,11.09,2851244922,251
7,"0.50X985XCOIL,CRNGO,SHT,SPEC-HG10062",COIL,80.0,11.80,2851244949,251
8,"0.50X785XCOIL,SPEC-AA10915.",COIL,80.0,12.98,2851244930,251
9,0.35 X 540 X COIL,COIL,80.0,22053.92,4670274090,25
10,0.50 X 892 X COIL,COIL,100.0,26.74,9099468784,208
11,0.50 X 892 X COIL,COIL,100.0,372.71,9069461102,316
12,0.50 X 892 X COIL,COIL,100.0,376.06,9069432803,104
13,0.35 X 780 X COIL,COIL,100.0,612.10,4323027923,315
14,0.50 X 495 MM X COILCRNGO (AA10901),COIL,100.0,3743.12,4981667030,373
15,0.4TKX50 COTTON TAPE,COTTON TAPE,60.0,116.00,2289026018,248
16,0.4TKX50 COTTON TAPE,COTTON TAPE,60.0,10356.78,7701505010,39
17,0.4X200 MM COPPER SHEET,COTTON TAPE,60.0,43050.00,1477806010,17
18,0.4TKX50 COTTON TAPE,COTTON TAPE,80.0,3.31,2851244850,199
19,0.4TKX50 COTTON TAPE,COTTON TAPE,80.0,5.43,2851244850,371